# Needs docker v2 since COMPOSE_PROJECT_NAME is not available in v1
version: '3.9'
networks:
  traefik:
    external: true

services:
  nyilund:
    image: '${IMAGE_NAME}'
    environment:
      NODE_ENV: production
    networks:
      - traefik
      - default
    restart: unless-stopped
    labels:
      - 'traefik.http.routers.$COMPOSE_PROJECT_NAME.rule=Host(`$DEPLOY_URL`)'