name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, closed, reopened, synchronize]
  release:
    types: [released, prereleased]

jobs:
  main:
    uses: esek/workflows/.github/workflows/main.yaml@main
    secrets: inherit
    with:
      prod_only: true
      disable_testing: true
